//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StBbcTriggerDetector_h
#define StBbcTriggerDetector_h
class StBbcTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StBbcTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UShort_t    mAdc[48];    //
   UShort_t    mTdc[48];    //
   UShort_t    mReg[2];     //
   UShort_t    mPed[128];    //
   UShort_t    mScl[32];     //
   UInt_t      mYear;        //
   UInt_t      mDSMVTX;      //

   StBbcTriggerDetector();
   StBbcTriggerDetector(const StBbcTriggerDetector & );
   virtual ~StBbcTriggerDetector();

   ClassDef(StBbcTriggerDetector,6); // Generated by MakeProject.
};
#endif
