//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StBTofHeader_h
#define StBTofHeader_h
class StBTofHeader;

#include "Rtypes.h"
#include "StObject.h"

class StBTofHeader : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Short_t     mFiberHeader[4];    //
   UInt_t      mFiberTriggerWord[4];    //
   UInt_t      mVpdHitPattern[2];       //
   Float_t     mVpdVz[20];              //
   Double_t    mTStart;                 //
   Double_t    mTStartErr;              //
   Double_t    mTDiff;                  //
   Double_t    mVpdTime[2][19];         //
   UInt_t      mTriggerTime[4];         //
   Short_t     mNTzero;                 //

   StBTofHeader();
   StBTofHeader(const StBTofHeader & );
   virtual ~StBTofHeader();

   ClassDef(StBTofHeader,3); // Generated by MakeProject.
};
#endif
