//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StBTofRawHit_h
#define StBTofRawHit_h
class StBTofRawHit;

#include "Rtypes.h"
#include "StObject.h"

class StBTofRawHit : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Char_t      mFlag;       //
   UChar_t     mTray;       //
   UChar_t     mChannel;    //
   UInt_t      mTdc;        //

   StBTofRawHit();
   StBTofRawHit(const StBTofRawHit & );
   virtual ~StBTofRawHit();

   ClassDef(StBTofRawHit,2); // Generated by MakeProject.
};
#endif
