//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StCtbTriggerDetector_h
#define StCtbTriggerDetector_h
class StCtbTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StCtbTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Float_t     mMips[120][2][11];    //
   Char_t      mTime[120][2][11];    //
   Float_t     mAux[16][11];         //
   Int_t       mNumberOfPreSamples;    //
   Int_t       mNumberOfPostSamples;    //

   StCtbTriggerDetector();
   StCtbTriggerDetector(const StCtbTriggerDetector & );
   virtual ~StCtbTriggerDetector();

   ClassDef(StCtbTriggerDetector,3); // Generated by MakeProject.
};
#endif
