//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StDcaGeometry_h
#define StDcaGeometry_h
class StDcaGeometry;

#include "Rtypes.h"
#include "StObject.h"

class StDcaGeometry : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Float_t     mImp;        //
   Float_t     mZ;          //
   Float_t     mPsi;        //
   Float_t     mPti;        //
   Float_t     mTan;        //
   Float_t     mCurv;       //
   Float_t     mImpImp;     //
   Float_t     mZImp;       //
   Float_t     mZZ;         //
   Float_t     mPsiImp;     //
   Float_t     mPsiZ;       //
   Float_t     mPsiPsi;     //
   Float_t     mPtiImp;     //
   Float_t     mPtiZ;       //
   Float_t     mPtiPsi;     //
   Float_t     mPtiPti;     //
   Float_t     mTanImp;     //
   Float_t     mTanZ;       //
   Float_t     mTanPsi;     //
   Float_t     mTanPti;     //
   Float_t     mTanTan;     //

   StDcaGeometry();
   StDcaGeometry(const StDcaGeometry & );
   virtual ~StDcaGeometry();

   ClassDef(StDcaGeometry,4); // Generated by MakeProject.
};
#endif
