//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StDetectorState_h
#define StDetectorState_h
class StDetectorState;

#include "Rtypes.h"
#include "StObject.h"

class StDetectorState : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mDetectorId;    //
   Bool_t      mIsGood;        //

   StDetectorState();
   StDetectorState(const StDetectorState & );
   virtual ~StDetectorState();

   ClassDef(StDetectorState,2); // Generated by MakeProject.
};
#endif
