//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StEmcTriggerDetector_h
#define StEmcTriggerDetector_h
class StEmcTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StEmcTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Char_t      mHighTower[300];    //High tower info from trigger patches
   Char_t      mPatch[300];        //Trigger patch sums
   Char_t      mEHighTower[90];    //Endcap high tower per patch
   Char_t      mEPatch[90];        //Endcap trigger patch sums
   unsigned short mBemcLayer1[48];    //Barrel layer 1 input 
   unsigned short mEemcLayer1[16];    //Endcap layer 1 input
   unsigned short mEmcLayer2[8];      //Combined EMC layer 2 input

   StEmcTriggerDetector();
   StEmcTriggerDetector(const StEmcTriggerDetector & );
   virtual ~StEmcTriggerDetector();

   ClassDef(StEmcTriggerDetector,4); // Generated by MakeProject.
};
#endif
