//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StEventInfo_h
#define StEventInfo_h
class StEventInfo;

#include "Rtypes.h"
#include "StObject.h"
#include <TString.h>

class StEventInfo : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   TString     mType;       //
   Int_t       mRunId;      //
   Int_t       mId;         //
   Int_t       mTime;       //
   UInt_t      mTriggerMask;    //
   UInt_t      mBunchCrossingNumber[2];    //
   UInt_t      mEventSize;                 //

   StEventInfo();
   StEventInfo(const StEventInfo & );
   virtual ~StEventInfo();

   ClassDef(StEventInfo,3); // Generated by MakeProject.
};
#endif
