//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StEventSummary_h
#define StEventSummary_h
class StEventSummary;

#include "Rtypes.h"
#include "StObject.h"
#include "TArrayL.h"
#include "StThreeVector_float_.h"
#include "TArrayF.h"

class StEventSummary : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mNumberOfTracks;    //
   Int_t       mNumberOfGoodTracks;    //
   Int_t       mNumberOfGoodPrimaryTracks;    //
   Int_t       mNumberOfPositiveTracks;       //
   Int_t       mNumberOfNegativeTracks;       //
   Int_t       mNumberOfExoticTracks;         //
   Int_t       mNumberOfVertices;             //
   TArrayL     mNumberOfVertexTypes;          //
   Int_t       mNumberOfPileupVertices;       //
   Float_t     mMeanPt;                       //
   Float_t     mMeanPt2;                      //
   Float_t     mMeanEta;                      //
   Float_t     mRmsEta;                       //
   StThreeVector<float> mPrimaryVertexPos;             //
   UShort_t             mVertexTypeArraySize;          //
   UShort_t             mPhiBinsSize;                  //
   UShort_t             mPtAndEtaBinsSize;             //
   UShort_t             mHistogramSize;                //
   TArrayF              mEtaBins;                      //
   TArrayF              mPtBins;                       //
   TArrayF              mPhiBins;                      //
   TArrayL              mEtaOfTracksHisto;             //
   TArrayL              mPtOfTracksHisto;              //
   TArrayL              mPhiOfTracksHisto;             //
   TArrayF              mEneryVsEtaHisto;              //
   TArrayF              mEnergyVsPhiHisto;             //
   Double_t             mMagneticFieldZ;               //

   StEventSummary();
   StEventSummary(const StEventSummary & );
   virtual ~StEventSummary();

   ClassDef(StEventSummary,3); // Generated by MakeProject.
};
#endif
