//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StFmsTriggerDetector_h
#define StFmsTriggerDetector_h
class StFmsTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StFmsTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UInt_t      mNumQTdata;    //
   UInt_t      mQTdata[1600];    //
   Char_t      mDSM[256];        //
   Char_t      mDSM01[112];      //
   Char_t      mDSM02[16];       //
   UShort_t    mDSM1[16];        //
   UShort_t    mDSM2[8];         //

   StFmsTriggerDetector();
   StFmsTriggerDetector(const StFmsTriggerDetector & );
   virtual ~StFmsTriggerDetector();

   ClassDef(StFmsTriggerDetector,5); // Generated by MakeProject.
};
#endif
