//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StFpdTriggerDetector_h
#define StFpdTriggerDetector_h
class StFpdTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StFpdTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UChar_t     mEN[49];     //
   UChar_t     mES[49];     //
   UChar_t     mET[25];     //
   UChar_t     mEB[25];     //
   UChar_t     mEPN[7];     //
   UChar_t     mEPS[7];     //
   UChar_t     mWN[49];     //
   UChar_t     mWS[49];     //
   UChar_t     mWT[25];     //
   UChar_t     mWB[25];     //
   UChar_t     mWPN[7];     //
   UChar_t     mWPS[7];     //
   UShort_t    mLayer1[2][6][4];    //
   UShort_t    mLayer2[2][6];       //

   StFpdTriggerDetector();
   StFpdTriggerDetector(const StFpdTriggerDetector & );
   virtual ~StFpdTriggerDetector();

   ClassDef(StFpdTriggerDetector,3); // Generated by MakeProject.
};
#endif
