//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StKinkMuDst_h
#define StKinkMuDst_h
class StKinkMuDst;

#include "Rtypes.h"
#include "StKinkBase.h"

class StKinkMuDst : public StKinkBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Float_t     mDcaParentDaughter;    //
   Float_t     mDcaDaughterPrimaryVertex;    //
   Float_t     mDcaParentPrimaryVertex;      //
   Float_t     mHitDistanceParentDaughter;    //
   Float_t     mHitDistanceParentVertex;      //
   Float_t     mMinDeltaEnergy;               //
   Float_t     mDecayAngle;                   //
   Float_t     mParentMomentum;               //
   Float_t     mParentPrimMomentum;           //
   Int_t       mParentCharge;                 //
   Float_t     mDaughterMomentum;             //
   Int_t       mDaughterCharge;               //
   Float_t     mDecayLength;                  //
   Float_t     mTransverseMomentum;           //
   Float_t     mTransverseMassKaon;           //
   Float_t     mTransverseMassPion;           //
   Float_t     mRapidityKaon;                 //
   Float_t     mRapidityPion;                 //
   Float_t     mChi2Kink;                     //
   Float_t     mClKink;                       //
   Float_t     mChi2Parent;                   //
   Float_t     mClParent;                     //
   Float_t     mChi2Daughter;                 //
   Float_t     mClDaughter;                   //
   Float_t     mDedxParent;                   //
   Float_t     mDedxDaughter;                 //
   Float_t     mErrDedxParent;                //
   Float_t     mErrDedxDaughter;              //
   UShort_t    mNumDedxParent;                //
   UShort_t    mNumDedxDaughter;              //
   Int_t       mKeyParent;                    //
   Int_t       mKeyDaughter;                  //

   StKinkMuDst();
   StKinkMuDst(const StKinkMuDst & );
   virtual ~StKinkMuDst();

   ClassDef(StKinkMuDst,10); // Generated by MakeProject.
};
#endif
