//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StKinkMc_h
#define StKinkMc_h
class StKinkMc;

#include "Rtypes.h"
#include "StKinkBase.h"

class StKinkMc : public StKinkBase {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mSimTpcHits;    //
   Int_t       mCommonTpcHits;    //
   Int_t       mDecayMode;        //

   StKinkMc();
   StKinkMc(const StKinkMc & );
   virtual ~StKinkMc();

   ClassDef(StKinkMc,6); // Generated by MakeProject.
};
#endif
