//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StL3AlgorithmInfo_h
#define StL3AlgorithmInfo_h
class StL3AlgorithmInfo;

#include "Rtypes.h"
#include "StObject.h"
#include "TArrayF.h"
#include "TArrayI.h"

class StL3AlgorithmInfo : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mId;         //
   Bool_t      mOn;         //
   Bool_t      mAccept;     //
   Bool_t      mBuild;      //
   Int_t       mNumberOfProcessedEvents;    //
   Int_t       mNumberOfAcceptedEvents;     //
   Int_t       mNumberOfBuildEvents;        //
   UShort_t    mDataSize;                   //
   TArrayF     mDataArray;                  //
   Int_t       mPreScale;                   //
   Int_t       mPostScale;                  //
   UShort_t    mIntParameterSize;           //
   TArrayI     mIntParameterArray;          //
   UShort_t    mFloatParameterSize;         //
   TArrayF     mFloatParameterArray;        //

   StL3AlgorithmInfo();
   StL3AlgorithmInfo(const StL3AlgorithmInfo & );
   virtual ~StL3AlgorithmInfo();

   ClassDef(StL3AlgorithmInfo,2); // Generated by MakeProject.
};
#endif
