//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMtdTriggerDetector_h
#define StMtdTriggerDetector_h
class StMtdTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StMtdTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short mADC[2][8];    //
   unsigned short mTDC[2][8];    //

   StMtdTriggerDetector();
   StMtdTriggerDetector(const StMtdTriggerDetector & );
   virtual ~StMtdTriggerDetector();

   ClassDef(StMtdTriggerDetector,2); // Generated by MakeProject.
};
#endif
