//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuEvent_h
#define StMuEvent_h
class StMuEvent;

#include "Rtypes.h"
#include "TObject.h"
#include "StRunInfo.h"
#include "StEventInfo.h"
#include "StEventSummary.h"
#include "StVpdTriggerDetector.h"
#include "StMtdTriggerDetector.h"
#include "StCtbTriggerDetector.h"
#include "StZdcTriggerDetector.h"
#include "StBbcTriggerDetector.h"
#include "StEmcTriggerDetector.h"
#include "StFpdTriggerDetector.h"
#include "StFmsTriggerDetector.h"
#include "StFpdCollection.h"
#include "StL0Trigger.h"
#include "StMuL3EventSummary.h"
#include "StMuTriggerIdCollection.h"
#include "StTriggerData.h"
#include "StThreeVector_float_.h"
#include "TArrayI.h"

class StMuEvent : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   StRunInfo   mRunInfo;    //
   StEventInfo mEventInfo;    //
   StEventSummary mEventSummary;    //
   StVpdTriggerDetector mVpdTriggerDetector;    //
   StMtdTriggerDetector mMtdTriggerDetector;    //
   StCtbTriggerDetector mCtbTriggerDetector;    //
   StZdcTriggerDetector mZdcTriggerDetector;    //
   StBbcTriggerDetector mBbcTriggerDetector;    //
   StEmcTriggerDetector mEmcTriggerDetector;    //
   StFpdTriggerDetector mFpdTriggerDetector;    //
   StFmsTriggerDetector mFmsTriggerDetector;    //
   StFpdCollection      mFpdCollection;         //
   StL0Trigger          mL0Trigger;             //
   StMuL3EventSummary   mL3EventSummary;        //
   StMuTriggerIdCollection mTriggerIdCollection;    //
   StTriggerData*          mTriggerData;            //
   UShort_t                mRefMultPos;             //
   UShort_t                mRefMultNeg;             //
   UShort_t                mRefMultFtpcEast;        //
   UShort_t                mRefMultFtpcWest;        //
   Float_t                 mReactionPlane[2];       //
   Float_t                 mReactionPlanePtWgt[2];    //
   UShort_t                mNHitsHFT[4];              //
   StThreeVector<float>    mPrimaryVertexError;       //
   TArrayI                 mL2Result;                 //Raw L2 info
   UInt_t                  mVpdEast;                  //VPD East Hit pattern 
   UInt_t                  mVpdWest;                  //VPD West Hit pattern
   Float_t                 mVpdTstart;                //VPD start time (calibrated)
   Float_t                 mVpdTdiff;                 //VPD time difference (calibrated)
   Float_t                 mVpdVz;                    //VPD vertex z

   StMuEvent();
   StMuEvent(const StMuEvent & );
   virtual ~StMuEvent();

   ClassDef(StMuEvent,15); // Generated by MakeProject.
};
#endif
