//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuFgtAdc_h
#define StMuFgtAdc_h
class StMuFgtAdc;

#include "Rtypes.h"
#include "TObject.h"

class StMuFgtAdc : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Short_t     mAdc;        //an ADC value
   Short_t     mTimeBin;    //the time bin number

   StMuFgtAdc();
   StMuFgtAdc(const StMuFgtAdc & );
   virtual ~StMuFgtAdc();

   ClassDef(StMuFgtAdc,2); // Generated by MakeProject.
};
#endif
