//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuPrimaryVertex_h
#define StMuPrimaryVertex_h
class StMuPrimaryVertex;

#include "Rtypes.h"
#include "TObject.h"
#include "StThreeVector_float_.h"

class StMuPrimaryVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mFlag;       //
   StThreeVector<float> mPosition;    //
   StThreeVector<float> mPosError;    //
   Int_t                mVertexFinderId;    //
   Float_t              mRanking;           //
   UShort_t             mNTracksUsed;       //
   UShort_t             mNBTOFMatch;        //
   UShort_t             mNCTBMatch;         //
   UShort_t             mNBEMCMatch;        //
   UShort_t             mNEEMCMatch;        //
   UShort_t             mNBTOFNotMatch;     //
   UShort_t             mNCTBNotMatch;      //
   UShort_t             mNBEMCNotMatch;     //
   UShort_t             mNEEMCNotMatch;     //
   UShort_t             mNCrossCentralMembrane;    //
   UShort_t             mNTracksWithPromptHit;     //
   UShort_t             mNPostXTracks;             //
   Float_t              mSumTrackPt;               //
   Float_t              mMeanDip;                  //
   Float_t              mChiSquared;               //
   UShort_t             mNTracks;                  //
   UShort_t             mNTpcWestOnly;             //
   UShort_t             mNTpcEastOnly;             //
   UShort_t             mRefMultNeg;               //
   UShort_t             mRefMultPos;               //
   UShort_t             mRefMultFtpcWest;          //
   UShort_t             mRefMultFtpcEast;          //
   UShort_t             mIdTruth;                  //MC vertex id if any 
   UShort_t             mQuality;                  //quality of this information (percentage of tracks coming the above MC Vertex)
   Int_t                mIdParent;                 //

   StMuPrimaryVertex();
   StMuPrimaryVertex(const StMuPrimaryVertex & );
   virtual ~StMuPrimaryVertex();

   ClassDef(StMuPrimaryVertex,9); // Generated by MakeProject.
};
#endif
