//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuFmsPoint_h
#define StMuFmsPoint_h
class StMuFmsPoint;

#include "Rtypes.h"
#include "TObject.h"
#include "StThreeVector_float_.h"
#include "TRef.h"

class StMuFmsPoint : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UShort_t    mDetectorId;    ///< Detector ID as defined in database
   Float_t     mEnergy;        ///< Total energy contained in the point
   Float_t     mX;             ///< Mean x ("center of gravity")
   Float_t     mY;             ///< Mean y ("center of gravity")
   Int_t       mId;            ///point Id
   StThreeVector<float> mXYZ;           //STAR coodinate XYZ
   TRef                 mCluster;       ///< Parent cluster of this photon

   StMuFmsPoint();
   StMuFmsPoint(const StMuFmsPoint & );
   virtual ~StMuFmsPoint();

   ClassDef(StMuFmsPoint,3); // Generated by MakeProject.
};
#endif
