//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuMtdRawHit_h
#define StMuMtdRawHit_h
class StMuMtdRawHit;

#include "Rtypes.h"
#include "TObject.h"

class StMuMtdRawHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Char_t      mFlag;       //
   UChar_t     mBackLeg;    //
   UChar_t     mChannel;    //
   UInt_t      mTdc;        //

   StMuMtdRawHit();
   StMuMtdRawHit(const StMuMtdRawHit & );
   virtual ~StMuMtdRawHit();

   ClassDef(StMuMtdRawHit,2); // Generated by MakeProject.
};
#endif
