//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuFgtStrip_h
#define StMuFgtStrip_h
class StMuFgtStrip;

#include "Rtypes.h"
#include "TObject.h"

class StMuFgtStrip : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mGeoId;      //indexing: 6 disk * 4 quad * 2 planes * 720 strips
   Int_t       mAdcStartIdx;    //index of ADC for first time bin in the ADC TClonesArray
   Short_t     mNumSavedTimeBins;    //the number of time bins saved in the ADC TClonesArray for this strip
   Short_t     mClusterSeedType;     //as defined in StEvent/StEnumerations.h
   Float_t     mCharge;              //before GEM, units (C), relation: ADC = ped + charge*gain(r,phi,disc)
   Float_t     mChargeUncert;        //

   StMuFgtStrip();
   StMuFgtStrip(const StMuFgtStrip & );
   virtual ~StMuFgtStrip();

   ClassDef(StMuFgtStrip,6); // Generated by MakeProject.
};
#endif
