//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuMtdHeader_h
#define StMuMtdHeader_h
class StMuMtdHeader;

#include "Rtypes.h"
#include "TObject.h"

class StMuMtdHeader : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   short       mFiberHeader1;    //
   short       mFiberHeader2;    //
   unsigned int mFiberTriggerWord1;    //
   unsigned int mFiberTriggerWord2;    //
   unsigned int mTriggerTime1;         //
   unsigned int mTriggerTime2;         //
   int          mShouldHaveRejectEvent;    //indication of event status in filtering
   unsigned int mTpcSectorMask;            //Mask of TPC sectors for tracking in the first iteration

   StMuMtdHeader();
   StMuMtdHeader(const StMuMtdHeader & );
   virtual ~StMuMtdHeader();

   ClassDef(StMuMtdHeader,3); // Generated by MakeProject.
};
#endif
