//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuMtdHit_h
#define StMuMtdHit_h
class StMuMtdHit;

#include "Rtypes.h"
#include "TObject.h"
#include <utility>

class StMuMtdHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UChar_t     mBackLeg;    //
   UChar_t     mModule;     //
   UChar_t     mCell;       //
   pair<Double_t,Double_t> mLeadingEdgeTime;    //
   pair<Double_t,Double_t> mTrailingEdgeTime;    //
   UShort_t                mIdTruth;             //simulation associated track id
   UShort_t                mQuality;             //quality of this information (percentage of charge produced by mIdTruth)
   UShort_t                mTrackKey;            //
   Int_t                   mIndex2Primary;       //
   Int_t                   mIndex2Global;        //

   StMuMtdHit();
   StMuMtdHit(const StMuMtdHit & );
   virtual ~StMuMtdHit();

   ClassDef(StMuMtdHit,3); // Generated by MakeProject.
};
#endif
