//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuEpdHit_h
#define StMuEpdHit_h
class StMuEpdHit;

#include "Rtypes.h"
#include "StObject.h"

class StMuEpdHit : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Short_t     mId;         //
   Int_t       mQTdata;     //
   Float_t     mnMIP;       //
   Int_t       mTruthId;    //

   StMuEpdHit();
   StMuEpdHit(const StMuEpdHit & );
   virtual ~StMuEpdHit();

   ClassDef(StMuEpdHit,2); // Generated by MakeProject.
};
#endif
