//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuPmdCluster_h
#define StMuPmdCluster_h
class StMuPmdCluster;

#include "Rtypes.h"
#include "TObject.h"

class StMuPmdCluster : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mSuperModule;    //
   Int_t       mNcell;          //
   Float_t     mEta;            //
   Float_t     mPhi;            //
   Float_t     mSigma;          //
   Float_t     mEnergy;         //
   Int_t       mEnergyPID;      //
   Int_t       mPID;            //
   Int_t       mMcPID;          //

   StMuPmdCluster();
   StMuPmdCluster(const StMuPmdCluster & );
   virtual ~StMuPmdCluster();

   ClassDef(StMuPmdCluster,2); // Generated by MakeProject.
};
#endif
