//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuTriggerIdCollection_h
#define StMuTriggerIdCollection_h
class StMuTriggerIdCollection;

#include "Rtypes.h"
#include "StObject.h"
#include "StTriggerId.h"

class StMuTriggerIdCollection : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   StTriggerId mL1TriggerId;    //
   StTriggerId mL2TriggerId;    //
   StTriggerId mL3TriggerId;    //
   StTriggerId mNTriggerId;     //When unrolling the TBranch, it's name exceeds the maximum. So we changed mNominalTriggerId to mNTriggerId 
   StTriggerId mLETriggerId;    //When unrolling the TBranch, it's name exceeds the maximum. So we changed mL3ExpandedTriggerId to mLETriggerId 

   StMuTriggerIdCollection();
   StMuTriggerIdCollection(const StMuTriggerIdCollection & );
   virtual ~StMuTriggerIdCollection();

   ClassDef(StMuTriggerIdCollection,3); // Generated by MakeProject.
};
#endif
