//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuBTofPidTraits_h
#define StMuBTofPidTraits_h
class StMuBTofPidTraits;

#include "Rtypes.h"
#include "TObject.h"
#include "StThreeVector_float_.h"

class StMuBTofPidTraits : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UChar_t     mMatchFlag;    //
   Float_t     mYLocal;       //
   Float_t     mZLocal;       //
   Float_t     mThetaLocal;    //
   StThreeVector<float> mPosition;      //
   Float_t              mTimeOfFlight;    //
   Float_t              mPathLength;      //
   Float_t              mBeta;            //
   Float_t              mSigmaElectron;    //
   Float_t              mSigmaPion;        //
   Float_t              mSigmaKaon;        //
   Float_t              mSigmaProton;      //
   Float_t              mProbElectron;     //
   Float_t              mProbPion;         //
   Float_t              mProbKaon;         //
   Float_t              mProbProton;       //

   StMuBTofPidTraits();
   StMuBTofPidTraits(const StMuBTofPidTraits & );
   virtual ~StMuBTofPidTraits();

   ClassDef(StMuBTofPidTraits,2); // Generated by MakeProject.
};
#endif
