//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuBTofHit_h
#define StMuBTofHit_h
class StMuBTofHit;

#include "Rtypes.h"
#include "StObject.h"

class StMuBTofHit : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UChar_t     mTray;       //
   UChar_t     mModule;     //
   UChar_t     mCell;       //
   Double_t    mLeadingEdgeTime;    //
   Double_t    mTrailingEdgeTime;    //
   Short_t     mAssociatedTrackId;    //
   Int_t       mIndex2Primary;        //
   Int_t       mIndex2Global;         //
   UShort_t    mIdTruth;              //
   UShort_t    mQuality;              //

   StMuBTofHit();
   StMuBTofHit(const StMuBTofHit & );
   virtual ~StMuBTofHit();

   ClassDef(StMuBTofHit,2); // Generated by MakeProject.
};
#endif
