//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuMcVertex_h
#define StMuMcVertex_h
class StMuMcVertex;

#include "Rtypes.h"
#include "TObject.h"
#include "StThreeVector_float_.h"

class StMuMcVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mId;         //
   Int_t       mNoDaughters;    //
   Int_t       mIdParTrk;       //
   Int_t       mIsInterm;       //
   Float_t     mTime;           //
   StThreeVector<float> mXyzV;           //

   StMuMcVertex();
   StMuMcVertex(const StMuMcVertex & );
   virtual ~StMuMcVertex();

   ClassDef(StMuMcVertex,2); // Generated by MakeProject.
};
#endif
