//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuMcTrack_h
#define StMuMcTrack_h
class StMuMcTrack;

#include "Rtypes.h"
#include "TObject.h"
#include "StThreeVector_float_.h"

class StMuMcTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mGePid;      //GEANT particle id 
   Int_t       mId;         //primary key 
   Bool_t      mIsShower;    //1 if shower track, 0 if not 
   UChar_t     mHits[22];    //Nhits in a detector 
   Int_t       mItrmdVertex;    //First intermediate vertex 
   Int_t       mIdVx;           //Id of start vertex of track 
   Int_t       mIdVxEnd;        //Id of stop vertex of this track 
   Char_t      mCharge;         //Charge 
   Float_t     mE;              //Energy 
   Float_t     mEta;            //Pseudorapidity 
   StThreeVector<float> mPxyz;           //Momentum 
   Float_t              mpT;             //Transverse momentum 
   Float_t              mPtot;           //Total momentum 
   Float_t              mRapidity;       //Rapidity 

   StMuMcTrack();
   StMuMcTrack(const StMuMcTrack & );
   virtual ~StMuMcTrack();

   ClassDef(StMuMcTrack,2); // Generated by MakeProject.
};
#endif
