//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuRpsCollection_h
#define StMuRpsCollection_h
class StMuRpsCollection;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#ifndef StMuRpsTrackPoint_h
#define StMuRpsTrackPoint_h
enum StMuRpsTrackPoint { kDefault_StMuRpsTrackPoint };
#ifdef __MAKECINT__
#pragma link C++ class StMuRpsTrackPoint+;
#endif
#endif
#ifndef StMuRpsTrack_h
#define StMuRpsTrack_h
enum StMuRpsTrack { kDefault_StMuRpsTrack };
#ifdef __MAKECINT__
#pragma link C++ class StMuRpsTrack+;
#endif
#endif

class StMuRpsCollection : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned char mSiliconBunch;    //
   int           mNumberPlanes[8];    //
   int           mNumberPlanesWithClusters[8];    //
   unsigned char mStatusRomanPot[8];              //
   int           mADC[8][2];                      //
   int           mTAC[8][2];                      //
   double        mOffsetPlane[8][4];              //
   double        mzPlane[8][4];                   //
   double        mAnglePlane[8][4];               //
   short         mOrientationPlane[8][4];         //
   unsigned char mStatusPlane[8][4];              //
   int           mNumberOfClusters[8][4];         //
   vector<double> mPositionCluster[8][4];          //
   vector<double> mPositionRMSCluster[8][4];       //
   vector<short>  mLengthCluster[8][4];            //
   vector<double> mEnergyCluster[8][4];            //
   vector<double> mXYCluster[8][4];                //
   vector<unsigned char> mQualityCluster[8][4];           //
   vector<StMuRpsTrackPoint*> mTrackPoints;                    //
   vector<StMuRpsTrack*>      mTracks;                         //

   StMuRpsCollection();
   StMuRpsCollection(const StMuRpsCollection & );
   virtual ~StMuRpsCollection();

   ClassDef(StMuRpsCollection,4); // Generated by MakeProject.
};
#endif
