//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuMtdCollection_h
#define StMuMtdCollection_h
class StMuMtdCollection;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "StMuMtdHeader.h"
#include "StMuMtdHit.h"
#include "StMuMtdRawHit.h"

class StMuMtdCollection : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<StMuMtdHeader> mMtdHeader;    //
   vector<StMuMtdHit>    mMtdHits;      //
   vector<StMuMtdRawHit> mMtdRawHits;    //

   StMuMtdCollection();
   StMuMtdCollection(const StMuMtdCollection & );
   virtual ~StMuMtdCollection();

   ClassDef(StMuMtdCollection,2); // Generated by MakeProject.
};
#endif
