//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuEmcTowerData_h
#define StMuEmcTowerData_h
class StMuEmcTowerData;

#include "Rtypes.h"
#include "TObject.h"

class StMuEmcTowerData : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short mTowerADC[4800];    //
   unsigned short mEndcapTowerADC[720];    //
   unsigned char  mBTowCrateFlags[30];     //
   unsigned char  mBSmdCrateFlags[8];      //
   unsigned char  mBPrsCrateFlags[4];      //
   unsigned char  mETowCrateFlags[6];      //
   unsigned char  mESmdCrateFlags[36];     //
   unsigned char  mEPrsCrateFlags[12];     //

   StMuEmcTowerData();
   StMuEmcTowerData(const StMuEmcTowerData & );
   virtual ~StMuEmcTowerData();

   ClassDef(StMuEmcTowerData,2); // Generated by MakeProject.
};
#endif
