//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuPmdHit_h
#define StMuPmdHit_h
class StMuPmdHit;

#include "Rtypes.h"
#include "TObject.h"

class StMuPmdHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Short_t     mSuperModule;    //
   Short_t     mSubDetector;    //
   Short_t     mRow;            //
   Short_t     mCol;            //
   Float_t     mEnergy;         //
   Int_t       mADC;            //

   StMuPmdHit();
   StMuPmdHit(const StMuPmdHit & );
   virtual ~StMuPmdHit();

   ClassDef(StMuPmdHit,2); // Generated by MakeProject.
};
#endif
