//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuTrack_h
#define StMuTrack_h
class StMuTrack;

#include "Rtypes.h"
#include "TObject.h"
#include "StTrackTopologyMap.h"
#include "StThreeVector_float_.h"
#include "StMuHelix.h"
#include "StMuProbPidTraits.h"
#include "StMuBTofPidTraits.h"
#include "StMuMtdPidTraits.h"

class StMuTrack : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mId;         //
   Short_t     mType;       //
   Short_t     mFlag;       //
   UInt_t      mFlagExtension;    //bit wise fast detector matching status
   Int_t       mIndex2Global;     //
   Int_t       mIndex2RichSpectra;    //
   Int_t       mIndex2BTofHit;        //dongx
   Int_t       mIndex2MtdHit;         //
   Int_t       mVertexIndex;          //Primary vertex id for this track's dca
   UChar_t     mNHits;                //Total number of points (was (F)tpc only)
   UChar_t     mNHitsPoss;            //Total possible points (was (F)tpc only)
   UChar_t     mNHitsDedx;            //
   UChar_t     mNHitsFit;             //Total fitted points (was (F)tpc only)
   UChar_t     mNHitsPossInner;       //Svt/Ist (3 bit) and Ssd (2 bit) possible hits, Pixel (3 bits)
   UChar_t     mNHitsFitInner;        //Svt/Ist (3 bit) and Ssd (2 bit) fitted hits, Pixel (3 bits)
   UChar_t     mNHitsPossTpc;         //Possible (F)tpc hits (Ftpc flagged with first 2 bits)
   UChar_t     mNHitsFitTpc;          //Fitted (F)tpc hits (Ftpc flagged with first 2 bits)
   UShort_t    mPidProbElectron;      //
   UShort_t    mPidProbPion;          //
   UShort_t    mPidProbKaon;          //
   UShort_t    mPidProbProton;        //
   Int_t       mNSigmaElectron;       //
   Int_t       mNSigmaPion;           //
   Int_t       mNSigmaKaon;           //
   Int_t       mNSigmaProton;         //
   Float_t     mdEdx;                 //
   Float_t     mChiSqXY;              //
   Float_t     mChiSqZ;               //
   Float_t     mPt;                   //
   Float_t     mEta;                  //
   Float_t     mPhi;                  //
   StTrackTopologyMap mTopologyMap;          //
   StThreeVector<float> mP;                    //
   StThreeVector<float> mDCA;                  //
   StThreeVector<float> mDCAGlobal;            //
   StThreeVector<float> mFirstPoint;           //
   StThreeVector<float> mLastPoint;            //
   StMuHelix            mHelix;                //
   StMuHelix            mOuterHelix;           //
   StMuProbPidTraits    mProbPidTraits;        ///< Class holding the new Yuri Fisyak pid probabilities.
   StMuBTofPidTraits    mBTofPidTraits;        /// dongx
   StMuMtdPidTraits     mMtdPidTraits;         /// Bingchu
   Int_t                mIndex2Cov;            //
   UShort_t             mIdTruth;              //MC track id if any 
   UShort_t             mQuality;              //quality of this information (percentage of hits coming the above MC track)
   Int_t                mIdParentVx;           //

   StMuTrack();
   StMuTrack(const StMuTrack & );
   virtual ~StMuTrack();

   ClassDef(StMuTrack,16); // Generated by MakeProject.
};
#endif
