//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuProbPidTraits_h
#define StMuProbPidTraits_h
class StMuProbPidTraits;

#include "Rtypes.h"
#include "TObject.h"

class StMuProbPidTraits : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned char mNDF;        //
   float         mdEdxFit;    //
   float         mdEdxErrorFit;    //
   float         mdEdxTruncated;    //
   float         mdEdxErrorTruncated;    //
   float         mdNdxFit;               //
   float         mdNdxErrorFit;          //
   float         mdEdxTrackLength;       //
   float         mLog2dX;                //
   float         mProbabilities[9];      ///< array holding the pid probabilities

   StMuProbPidTraits();
   StMuProbPidTraits(const StMuProbPidTraits & );
   virtual ~StMuProbPidTraits();

   ClassDef(StMuProbPidTraits,6); // Generated by MakeProject.
};
#endif
