//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuFmsHit_h
#define StMuFmsHit_h
class StMuFmsHit;

#include "Rtypes.h"
#include "TObject.h"

class StMuFmsHit : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UShort_t    mDetectorId;    //Detector Id
   UShort_t    mChannel;       //Channel in the detector
   UShort_t    mQTCrtSlotCh;    //QT Crate/Slot/Ch, 4 bits for Crate and Slot, 8 bits for channal
   UShort_t    mAdc;            //ADC values
   UShort_t    mTdc;            //TDC values
   Float_t     mEnergy;         //corrected energy

   StMuFmsHit();
   StMuFmsHit(const StMuFmsHit & );
   virtual ~StMuFmsHit();

   ClassDef(StMuFmsHit,3); // Generated by MakeProject.
};
#endif
