//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StMuFgtCluster_h
#define StMuFgtCluster_h
class StMuFgtCluster;

#include "Rtypes.h"
#include "TObject.h"

class StMuFgtCluster : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mCentralStripGeoId;    //obvious--also serves as a unique key, and
   Int_t       mFirstStripAssociationIdx;    //Index in the MuDst mFgtStripAssociation
   Int_t       mMaxTimeBin;                  //time bin for max adc
   Int_t       mMaxAdc;                      //max adc in all strips and timebin
   Int_t       mNumStrips;                   //number of strips associated with this cluster
   Float_t     mCharge;                      //
   Float_t     mChargeUncert;                //associated charge for the cluster, and its uncertainty
   Float_t     mR;                           //
   Float_t     mErrR;                        //
   Float_t     mPhi;                         //
   Float_t     mErrPhi;                      //r, phi position and error
   Float_t     mEvenOddChargeAsy;            //(even-odd)/sum charge for phi layer

   StMuFgtCluster();
   StMuFgtCluster(const StMuFgtCluster & );
   virtual ~StMuFgtCluster();

   ClassDef(StMuFgtCluster,5); // Generated by MakeProject.
};
#endif
