//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StRichSpectra_h
#define StRichSpectra_h
class StRichSpectra;

#include "Rtypes.h"
#include "StObject.h"

class StRichSpectra : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Float_t     mExtrapolatedX;    //
   Float_t     mExtrapolatedY;    //
   Float_t     mDx;               //
   Float_t     mDy;               //
   Float_t     mCdx;              //
   Float_t     mCdy;              //
   Float_t     mCherenkovAngle;    //
   Float_t     mCherenkovAngleSigma;    //
   Int_t       mNumberOfPhotons;        //
   Float_t     mPeakAngle;              //
   Int_t       mPeakPhotons;            //
   Int_t       mTotalPhotons;           //
   Float_t     mMassSquared;            //
   Float_t     mLineIntegralRatio;      //
   Float_t     mLineIntegral;           //
   Float_t     mAlpha;                  //
   Int_t       mFlag;                   //
   Float_t     mReserved;               //
   Float_t     mDpi;                    //
   Float_t     mDk;                     //
   Float_t     mDp;                     //
   Int_t       mNDpi;                   //
   Int_t       mNDk;                    //
   Int_t       mNDp;                    //
   Int_t       mVersion;                //

   StRichSpectra();
   StRichSpectra(const StRichSpectra & );
   virtual ~StRichSpectra();

   ClassDef(StRichSpectra,2); // Generated by MakeProject.
};
#endif
