//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StRunInfo_h
#define StRunInfo_h
class StRunInfo;

#include "Rtypes.h"
#include "StObject.h"
#include <TString.h>

class StRunInfo : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mRunId;      //
   UInt_t      mProductionTime;    //
   TString     mProductionVersion;    //
   Float_t     mCenterOfMassEnergy;    //
   Int_t       mBeamMassNumber[2];     //
   Double_t    mMagneticFieldZ;        //
   Float_t     mTpcDriftVelocity[2];    //
   Float_t     mSvtDriftVelocityScaler;    //
   Double_t    mZdcEastRate;               //
   Double_t    mZdcWestRate;               //
   Double_t    mZdcCoincidenceRate;        //
   Double_t    mBackgroundRate;            //
   Double_t    mL0RateToRich;              //
   Double_t    mBbcCoincidenceRate;        //
   Float_t     mBeamEnergy[2];             //
   Float_t     mInitialBeamIntensity[2];    //
   Float_t     mBeamLifeTime[2];            //
   Float_t     mBeamFillNumber[2];          //
   Double_t    mBbcEastRate;                //
   Double_t    mBbcWestRate;                //
   Double_t    mBbcBlueBackgroundRate;      //
   Double_t    mBbcYellowBackgroundRate;    //
   Int_t       mSpaceChargeCorrectionMode;    //
   Float_t     mSpaceCharge;                  //

   StRunInfo();
   StRunInfo(const StRunInfo & );
   virtual ~StRunInfo();

   ClassDef(StRunInfo,8); // Generated by MakeProject.
};
#endif
