//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StStrangeEvMuDst_h
#define StStrangeEvMuDst_h
class StStrangeEvMuDst;

#include "Rtypes.h"
#include "StStrangeMuDst.h"

class StStrangeEvMuDst : public StStrangeMuDst {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mRun;        //
   Int_t       mEvent;      //
   Float_t     mPrimaryVertexX;    //
   Float_t     mPrimaryVertexY;    //
   Float_t     mPrimaryVertexZ;    //
   Int_t       mGlobalTracks;      //
   Int_t       mPrimaryTracks;     //
   Int_t       mPrimaryNegTracks;    //
   Float_t     mMagneticField;       //
   UInt_t      mL0TriggerWord;       //

   StStrangeEvMuDst();
   StStrangeEvMuDst(const StStrangeEvMuDst & );
   virtual ~StStrangeEvMuDst();

   ClassDef(StStrangeEvMuDst,9); // Generated by MakeProject.
};
#endif
