//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StStrangeAssoc_h
#define StStrangeAssoc_h
class StStrangeAssoc;

#include "Rtypes.h"
#include "TObject.h"

class StStrangeAssoc : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mIndexRecoArray;    //
   Int_t       mIndexMcArray;      //

   StStrangeAssoc();
   StStrangeAssoc(const StStrangeAssoc & );
   virtual ~StStrangeAssoc();

   ClassDef(StStrangeAssoc,4); // Generated by MakeProject.
};
#endif
