//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StThreeVector_float__h
#define StThreeVector_float__h
template <typename T0> class StThreeVector;
template <> class StThreeVector<float>;

#include "Rtypes.h"

template <typename T0> class StThreeVector;
template <> class StThreeVector<float> {

public:
// Nested classes declaration.

public:
// Data Members.
   float       mX1;         //
   float       mX2;         //
   float       mX3;         //

   StThreeVector();
   StThreeVector(const StThreeVector & );
   virtual ~StThreeVector();

   ClassDef(StThreeVector,4); // Generated by MakeProject.
};
#endif
