//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StTofRawData_h
#define StTofRawData_h
class StTofRawData;

#include "Rtypes.h"
#include "StObject.h"

class StTofRawData : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UShort_t    mLeTeFlag;    //
   UShort_t    mTray;        //
   UShort_t    mChannel;     //
   UInt_t      mTdc;         //
   UInt_t      mTriggertime;    //
   UShort_t    mQuality;        //

   StTofRawData();
   StTofRawData(const StTofRawData & );
   virtual ~StTofRawData();

   ClassDef(StTofRawData,4); // Generated by MakeProject.
};
#endif
