//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StTofData_h
#define StTofData_h
class StTofData;

#include "Rtypes.h"
#include "StObject.h"

class StTofData : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   UShort_t    mDataIndex;    //
   UShort_t    mAdc;          //
   UShort_t    mTdc;          //
   Short_t     mTc;           //
   UShort_t    mSc;           //
   UInt_t      mLeadingTdc;    //
   UInt_t      mTrailingTdc;    //

   StTofData();
   StTofData(const StTofData & );
   virtual ~StTofData();

   ClassDef(StTofData,4); // Generated by MakeProject.
};
#endif
