//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StTriggerData_h
#define StTriggerData_h
class StTriggerData;

#include "Rtypes.h"
#include "StObject.h"

class StTriggerData : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         mYear;       //
   float       mZdcVertexZ;    //
   int         mRun;           //
   unsigned int mErrorFlag;     //

   StTriggerData();
   StTriggerData(const StTriggerData & );
   virtual ~StTriggerData();

   ClassDef(StTriggerData,8); // Generated by MakeProject.
};
#endif
