//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StTriggerId_h
#define StTriggerId_h
class StTriggerId;

#include "Rtypes.h"
#include "StObject.h"

class StTriggerId : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   ULong64_t   mMask;       //
   UInt_t      mId[64];     //
   UInt_t      mVersion[64];    //
   UInt_t      mNameVersion[64];    //
   UInt_t      mThresholdVersion[64];    //
   UInt_t      mPrescaleVersion[64];     //

   StTriggerId();
   StTriggerId(const StTriggerId & );
   virtual ~StTriggerId();

   ClassDef(StTriggerId,6); // Generated by MakeProject.
};
#endif
