//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StV0Mc_h
#define StV0Mc_h
class StV0Mc;

#include "Rtypes.h"
#include "StStrangeMuDst.h"
#include "StV0I.h"

class StV0Mc : public StStrangeMuDst , public StV0I {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mPositiveSimTpcHits;    //
   Int_t       mPositiveCommonTpcHits;    //
   Int_t       mNegativeSimTpcHits;       //
   Int_t       mNegativeCommonTpcHits;    //
   Int_t       mDecayMode;                //
   Int_t       mParentGeantId;            //
   Int_t       mPositiveGeantId;          //
   Int_t       mNegativeGeantId;          //
   Float_t     mParentMomentumX;          //
   Float_t     mParentMomentumY;          //
   Float_t     mParentMomentumZ;          //
   Float_t     mPositiveMomentumX;        //
   Float_t     mPositiveMomentumY;        //
   Float_t     mPositiveMomentumZ;        //
   Float_t     mNegativeMomentumX;        //
   Float_t     mNegativeMomentumY;        //
   Float_t     mNegativeMomentumZ;        //
   Float_t     mPositionX;                //
   Float_t     mPositionY;                //
   Float_t     mPositionZ;                //

   StV0Mc();
   StV0Mc(const StV0Mc & );
   virtual ~StV0Mc();

   ClassDef(StV0Mc,6); // Generated by MakeProject.
};
#endif
