//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StV0I_h
#define StV0I_h
class StV0I;

#include "Rtypes.h"

class StV0I {

public:
// Nested classes declaration.

public:
// Data Members.

   StV0I();
   StV0I(const StV0I & );
   virtual ~StV0I();

};
#endif
