//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StVpdTriggerDetector_h
#define StVpdTriggerDetector_h
class StVpdTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StVpdTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned short mADC[2][16];    //
   unsigned short mTDC[2][16];    //
   unsigned short mADCmxq[2][16];    //WJL
   unsigned short mTDCmxq[2][16];    //WJL
   unsigned short mEarliestTDC[2];    //
   unsigned short mTimeDifference;    //
   unsigned short mYear;              //

   StVpdTriggerDetector();
   StVpdTriggerDetector(const StVpdTriggerDetector & );
   virtual ~StVpdTriggerDetector();

   ClassDef(StVpdTriggerDetector,4); // Generated by MakeProject.
};
#endif
