//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StXiMuDst_h
#define StXiMuDst_h
class StXiMuDst;

#include "Rtypes.h"
#include "StV0MuDst.h"
#include "StXiI.h"
#include "StTrackTopologyMap.h"

class StXiMuDst : public StV0MuDst , public StXiI {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       mCharge;     //Written out
   Float_t     mDecayVertexXiX;    //
   Float_t     mDecayVertexXiY;    //
   Float_t     mDecayVertexXiZ;    //
   Float_t     mDcaXiDaughters;    //
   Float_t     mDcaBachelorToPrimVertex;    //
   Float_t     mDcaXiToPrimVertex;          //
   Float_t     mMomBachelorX;               //
   Float_t     mMomBachelorY;               //
   Float_t     mMomBachelorZ;               //
   Int_t       mKeyBachelor;                //
   StTrackTopologyMap mTopologyMapBachelor;        //
   Float_t            mChi2Xi;                     //
   Float_t            mClXi;                       //
   Float_t            mChi2Bachelor;               //
   Float_t            mClBachelor;                 //
   Float_t            mDedxBachelor;               //
   Float_t            mErrDedxBachelor;            //
   UShort_t           mNumDedxBachelor;            //

   StXiMuDst();
   StXiMuDst(const StXiMuDst & );
   virtual ~StXiMuDst();

   ClassDef(StXiMuDst,9); // Generated by MakeProject.
};
#endif
