//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StXiMc_h
#define StXiMc_h
class StXiMc;

#include "Rtypes.h"
#include "StKinkMc.h"
#include "StXiI.h"

class StXiMc : public StKinkMc , public StXiI {

public:
// Nested classes declaration.

public:
// Data Members.
   Int_t       v0;          //

   StXiMc();
   StXiMc(const StXiMc & );
   virtual ~StXiMc();

   ClassDef(StXiMc,8); // Generated by MakeProject.
};
#endif
