//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StXiI_h
#define StXiI_h
class StXiI;

#include "Rtypes.h"
#include "StV0I.h"

class StXiI : public StV0I {

public:
// Nested classes declaration.

public:
// Data Members.

   StXiI();
   StXiI(const StXiI & );
   virtual ~StXiI();

};
#endif
