//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef StZdcTriggerDetector_h
#define StZdcTriggerDetector_h
class StZdcTriggerDetector;

#include "Rtypes.h"
#include "StObject.h"

class StZdcTriggerDetector : public StObject {

public:
// Nested classes declaration.

public:
// Data Members.
   Float_t     mAdc[16];    //
   Float_t     mTdc[16];    //
   Float_t     mSumAdc[2];    //
   Float_t     mSum;          //
   Float_t     mVertexZ;      //
   Float_t     mZdcSmdEast[16];    //
   Float_t     mZdcSmdWest[16];    //

   StZdcTriggerDetector();
   StZdcTriggerDetector(const StZdcTriggerDetector & );
   virtual ~StZdcTriggerDetector();

   ClassDef(StZdcTriggerDetector,4); // Generated by MakeProject.
};
#endif
