//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef TrgOfflen2016_h
#define TrgOfflen2016_h
class TrgOfflen2016;

#include "Rtypes.h"

class TrgOfflen2016 {

public:
// Nested classes declaration.

public:
// Data Members.
   int         offset;      //Offset (in bytes) from the start of Trigger block to data 
   int         length;      //Length (in bytes) of data 

   TrgOfflen2016();
   TrgOfflen2016(const TrgOfflen2016 & );
   virtual ~TrgOfflen2016();

};
#endif
