//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul 23 18:55:02 2018 by ROOT version 6.13/04)
//      from the StreamerInfo in file sb/install-star-cvs-deb-32-root5-gcc4/st_physics_17135012_raw_2000025.MuDst.root
//////////////////////////////////////////////////////////


#ifndef TriggerDataBlk2016_h
#define TriggerDataBlk2016_h
class TriggerDataBlk2016;

#include "Rtypes.h"
#include "TrgOfflen2016.h"

class TriggerDataBlk2016 {

public:
// Nested classes declaration.

public:
// Data Members.
   int         FormatVersion;    //Trigger Data Definition Version yymmddvv 
   int         totalTriggerLength;    //Total length (bytes) of complete Trigger Block 
   int         eventNumber;           //Event number in this run 
   TrgOfflen2016 EventDesc_ofl;         //Offset/length pair to Event Descriptor 
   TrgOfflen2016 L1_DSM_ofl;            //Offset/length pair to L1 DSM Data 
   TrgOfflen2016 Summary_ofl;           //Offset/length pair to Summary Data 
   TrgOfflen2016 MainX[20];             //Offset/length pairs for main crossing 
   int           PrePostList[10];       //Offsets to offset/length pairs to Pre and Post crossing 
   int           raw_data[30724];       //Storage for raw data 

   TriggerDataBlk2016();
   TriggerDataBlk2016(const TriggerDataBlk2016 & );
   virtual ~TriggerDataBlk2016();

};
#endif
